In [72]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [73]:
np.random.seed(42)

In [74]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 0], df.iloc[:, 1], test_size=.2, random_state=0)

In [75]:
#Generate n synthetic samples (not a real dataset, randomly generated)
n=100

#Class 0
X1 = np.random.normal(loc=-2.0, scale=2, size=int(n/2))
Y1 = np.random.normal(loc=0, scale=1, size=int(n/2))
print(X1)
print(Y1)

#Class 1
X2 = np.random.normal(loc=2.0, scale=2.0, size=int(n/2))
Y2 = np.random.normal(loc=0, scale=1.0, size=int(n/2))

[-1.00657169 -2.2765286  -0.70462292  1.04605971 -2.46830675 -2.46827391
  1.15842563 -0.46513054 -2.93894877 -0.91487991 -2.92683539 -2.93145951
 -1.51607546 -5.82656049 -5.44983567 -3.12457506 -4.02566224 -1.37150533
 -3.81604815 -4.8246074   0.93129754 -2.4515526  -1.86494359 -4.84949637
 -3.08876545 -1.77815482 -4.30198715 -1.24860396 -3.20127738 -2.5833875
 -3.20341322  1.70455637 -2.02699445 -4.11542186 -0.35491018 -4.4416873
 -1.58227281 -5.91934025 -4.6563721  -1.60627753 -0.52306684 -1.65726344
 -2.23129656 -2.60220739 -4.95704398 -3.43968842 -2.92127754  0.11424445
 -1.31276342 -5.52608031]
[ 0.32408397 -0.38508228 -0.676922    0.61167629  1.03099952  0.93128012
 -0.83921752 -0.30921238  0.33126343  0.97554513 -0.47917424 -0.18565898
 -1.10633497 -1.19620662  0.81252582  1.35624003 -0.07201012  1.0035329
  0.36163603 -0.64511975  0.36139561  1.53803657 -0.03582604  1.56464366
 -2.6197451   0.8219025   0.08704707 -0.29900735  0.09176078 -1.98756891
 -0.21967189  0.35711257  1.

In [78]:
# Create dataset from dim1, dim2, and output label (0 or 1)

ds1 = np.empty([n, 3])

size = int(n/2)

for i in range(size):
        ds1[i] = [X1[i], Y1[i], 0]
        ds1[i+size] = [X2[i], Y2[i], 1]
      
print(ds1)
        
# print(ds1[:, :-1])
print(ds1[:, -1])

[[-1.00657169e+00  3.24083969e-01  0.00000000e+00]
 [-2.27652860e+00 -3.85082280e-01  0.00000000e+00]
 [-7.04622924e-01 -6.76922000e-01  0.00000000e+00]
 [ 1.04605971e+00  6.11676289e-01  0.00000000e+00]
 [-2.46830675e+00  1.03099952e+00  0.00000000e+00]
 [-2.46827391e+00  9.31280119e-01  0.00000000e+00]
 [ 1.15842563e+00 -8.39217523e-01  0.00000000e+00]
 [-4.65130542e-01 -3.09212376e-01  0.00000000e+00]
 [-2.93894877e+00  3.31263431e-01  0.00000000e+00]
 [-9.14879913e-01  9.75545127e-01  0.00000000e+00]
 [-2.92683539e+00 -4.79174238e-01  0.00000000e+00]
 [-2.93145951e+00 -1.85658977e-01  0.00000000e+00]
 [-1.51607546e+00 -1.10633497e+00  0.00000000e+00]
 [-5.82656049e+00 -1.19620662e+00  0.00000000e+00]
 [-5.44983567e+00  8.12525822e-01  0.00000000e+00]
 [-3.12457506e+00  1.35624003e+00  0.00000000e+00]
 [-4.02566224e+00 -7.20101216e-02  0.00000000e+00]
 [-1.37150533e+00  1.00353290e+00  0.00000000e+00]
 [-3.81604815e+00  3.61636025e-01  0.00000000e+00]
 [-4.82460740e+00 -6.45119755e-

In [77]:
x_train, x_test, y_train, y_test = train_test_split(ds1[:, :-1])

ValueError: not enough values to unpack (expected 4, got 2)